### ISSUE TITLE
Rendu 1

### ISSUE THREAD

**Issue by noah-bar** [CPNV-ES-EXTRA-LABOS/lb-nginx-ms#3]
@NicolasGlassey 
Nous sommes vendredi, je vous livre donc le projet comme convenu. 

Tout le code nécessaire pour déployer l'infrastructure se trouve sur la branche [develop](https://github.com/CPNV-ES-EXTRA-LABOS/lb-nginx-ms/tree/develop).

**IT**
Toutes les fonctionnalités demandées ont été, me semble-t-il, implémentées.

**Math**
J'ai fait de mon mieux pour répondre aux objectifs en comparant au maximum les différentes stratégies de répartition de charge. Vous trouverez tous les détails dans le [rapport](https://eduvaud-my.sharepoint.com/:b:/r/personal/noah_barberini_eduvaud_ch/Documents/barberini-travail-supp/lb-nginx-ms-rapport.pdf?csf=1&web=1&e=RnEhDM).

**Défense**
Pour la défense qui aura lieu lundi, souhaitez-vous une présentation type PowerPoint ou une présentation des différents points (démonstration fonctionnelle de l'infrastructure, génération des graphiques, etc.) suffit-elle ?

Bon week-end et à lundi !

**Comment by NicolasGlassey** [comment]
@noah-bar 

Pour la défense, voici ce que j'avais mentionné dans le readme:

```
Une défense finale sur le site de Ste-Croix, le lundi 24 juin, 10h00:

    Démonstration fonctionnelle de l'infra.
    Capture de métriques.
    Génération des graphiques.
    Explications mathématiques des stratégies de répartitions de charges (graphiques, fonctions mathématiques utilisées).
```

Il me semble que cela répond à vos demandes, non ? Redites-moi si besoin.
